// Copyright (c) Yug Bargaway under Apache License 2.0
// See LICENSE.txt for details.

// This file is generated by Gemini 3.8 flash, so this file uses LLM-generated code,
// rest files in rtl is written by me. Any issue you face, kindly mention in the issues
// sections in github.


`timescale 1ns / 1ps
`default_nettype none


`include "minirisc_defs.vh"


module alu_tb;

    localparam integer WORD_w = 32;
    localparam integer CTRL_w = 4;

    reg [WORD_w-1:0] inputA;
    reg [WORD_w-1:0] inputB;
    reg [CTRL_w-1:0] ALUctrl;

    wire [WORD_w-1:0] ALUout;
    wire ALUovfl;
    wire zero;
    wire negative;

    integer errors = 0;
    integer test_count = 0;

    // Device under test
    alu #(
        .WORD_w(WORD_w),
        .CTRL_w(CTRL_w)
    ) dut (
        .inputA   (inputA),
        .inputB   (inputB),
        .ALUctrl  (ALUctrl),
        .ALUout   (ALUout),
        .ALUovfl  (ALUovfl),
        .zero     (zero),
        .negative (negative)
    );

    
    initial begin
        #100000;
        $display("FAIL: timeout");
        $finish;
    end

    
    initial begin
        $dumpfile("waves/alu_tb.vcd");
        $dumpvars(0, alu_tb);
    end

    task check(
        input [WORD_w-1:0] exp_out,
        input              exp_ovfl,
        input              exp_zero,
        input              exp_neg,
        input [160:0]      test_name
    );
    begin
        #1;
        test_count = test_count + 1;
        if (ALUout !== exp_out || ALUovfl !== exp_ovfl || zero !== exp_zero || negative !== exp_neg) begin
            $display("FAIL mismatch in [%0s]: A=0x%08h, B=0x%08h, ctrl=%0d | Got: out=0x%08h ovfl=%0b z=%0b neg=%0b | Expected: out=0x%08h ovfl=%0b z=%0b neg=%0b",
                     test_name, inputA, inputB, ALUctrl, ALUout, ALUovfl, zero, negative, exp_out, exp_ovfl, exp_zero, exp_neg);
            errors = errors + 1;
        end
    end
    endtask

    initial begin 

        // Add functionalitites
        ALUctrl = `ALU_add;
        inputA = 32'd15; inputB = 32'd25;
        check(32'd40, 1'b0, 1'b0, 1'b0, "ADD: 15 + 25");

        inputA = 32'd0; inputB = 32'd0;
        check(32'd0, 1'b0, 1'b1, 1'b0, "ADD: 0 + 0 (zero flag)");

        inputA = 32'h7FFFFFFF; inputB = 32'd1;
        check(32'h80000000, 1'b1, 1'b0, 1'b1, "ADD: POS + POS -> NEG (overflow)");

        inputA = 32'h80000000; inputB = 32'h80000000;
        check(32'h00000000, 1'b1, 1'b1, 1'b0, "ADD: NEG + NEG -> 0 (overflow & zero)");

        inputA = 32'h7FFFFFFF; inputB = 32'hFFFFFFFF; // -1
        check(32'h7FFFFFFE, 1'b0, 1'b0, 1'b0, "ADD: POS + NEG (no overflow)");

        inputA = 32'h80000000; inputB = 32'd1;
        check(32'h80000001, 1'b0, 1'b0, 1'b1, "ADD: MIN_INT + 1 (neg, no ovfl)");


        // SUB functionality
        ALUctrl = `ALU_sub;
        inputA = 32'd40; inputB = 32'd15;
        check(32'd25, 1'b0, 1'b0, 1'b0, "SUB: 40 - 15");

        inputA = 32'd25; inputB = 32'd25;
        check(32'd0, 1'b0, 1'b1, 1'b0, "SUB: 25 - 25 (zero flag)");

        inputA = 32'd10; inputB = 32'd20;
        check(-32'd10, 1'b0, 1'b0, 1'b1, "SUB: 10 - 20 (negative flag)");

        inputA = 32'h80000000; inputB = 32'd1;
        check(32'h7FFFFFFF, 1'b1, 1'b0, 1'b0, "SUB: NEG - POS -> POS (overflow)");

        inputA = 32'h7FFFFFFF; inputB = 32'hFFFFFFFF; // -1
        check(32'h80000000, 1'b1, 1'b0, 1'b1, "SUB: POS - NEG -> NEG (overflow)");

        inputA = 32'd0; inputB = 32'd1;
        check(32'hFFFFFFFF, 1'b0, 1'b0, 1'b1, "SUB: 0 - 1 = -1 (no ovfl)");


        // Logical Operators
        ALUctrl = `ALU_and;
        inputA = 32'hF0F0AAAA; inputB = 32'h0FF05555;
        check(32'h00F00000, 1'b0, 1'b0, 1'b0, "AND: bitwise");

        inputA = 32'hF0F0AAAA; inputB = 32'h0F0F5555;
        check(32'h00000000, 1'b0, 1'b1, 1'b0, "AND: result zero");

        ALUctrl = `ALU_or;
        inputA = 32'hF0F00000; inputB = 32'h0000AAAA;
        check(32'hF0F0AAAA, 1'b0, 1'b0, 1'b1, "OR: bitwise");

        inputA = 32'h00000000; inputB = 32'h00000000;
        check(32'h00000000, 1'b0, 1'b1, 1'b0, "OR: result zero");

        ALUctrl = `ALU_xor;
        inputA = 32'hFFFF0000; inputB = 32'hAAAA5555;
        check(32'h55555555, 1'b0, 1'b0, 1'b0, "XOR: bitwise");

        inputA = 32'h12345678; inputB = 32'h12345678;
        check(32'h00000000, 1'b0, 1'b1, 1'b0, "XOR: A ^ A (zero)");

        ALUctrl = `ALU_nor;
        inputA = 32'h00000000; inputB = 32'h00000000;
        check(32'hFFFFFFFF, 1'b0, 1'b0, 1'b1, "NOR: ~(0 | 0) = -1");

        inputA = 32'hFFFFFFFF; inputB = 32'h00000000;
        check(32'h00000000, 1'b0, 1'b1, 1'b0, "NOR: result zero");

        ALUctrl = `ALU_not;
        inputA = 32'hAAAA5555; inputB = 32'h0;
        check(32'h5555AAAA, 1'b0, 1'b0, 1'b0, "NOT: ~A");

        inputA = 32'hFFFFFFFF; inputB = 32'h0;
        check(32'h00000000, 1'b0, 1'b1, 1'b0, "NOT: ~(-1) = 0");


        // Shift Operators
        ALUctrl = `ALU_sll;
        inputA = 32'h00000001; inputB = 32'd0;
        check(32'h00000001, 1'b0, 1'b0, 1'b0, "SLL: shift by 0");

        inputA = 32'h00000001; inputB = 32'd31;
        check(32'h80000000, 1'b0, 1'b0, 1'b1, "SLL: 1 << 31");

        inputA = 32'h00000001; inputB = 32'd4;
        check(32'h00000010, 1'b0, 1'b0, 1'b0, "SLL: 1 << 4");

        ALUctrl = `ALU_srl;
        inputA = 32'h80000000; inputB = 32'd1;
        check(32'h40000000, 1'b0, 1'b0, 1'b0, "SRL: logical right shift by 1");

        inputA = 32'h80000000; inputB = 32'd31;
        check(32'h00000001, 1'b0, 1'b0, 1'b0, "SRL: logical right shift by 31");

        inputA = 32'h80000000; inputB = 32'd0;
        check(32'h80000000, 1'b0, 1'b0, 1'b1, "SRL: logical right shift by 0");

        ALUctrl = `ALU_sra;
        inputA = 32'h80000000; inputB = 32'd1;
        check(32'hC0000000, 1'b0, 1'b0, 1'b1, "SRA: arithmetic right shift by 1");

        inputA = 32'h80000000; inputB = 32'd31;
        check(32'hFFFFFFFF, 1'b0, 1'b0, 1'b1, "SRA: arithmetic right shift by 31");

        inputA = 32'h70000000; inputB = 32'd4;
        check(32'h07000000, 1'b0, 1'b0, 1'b0, "SRA: positive operand shift");

        inputA = 32'h80000000; inputB = 32'd0;
        check(32'h80000000, 1'b0, 1'b0, 1'b1, "SRA: shift by 0");


        // Signed Comparisons
        ALUctrl = `ALU_slt;
        inputA = -32'd1; inputB = 32'd1;
        check(32'd1, 1'b0, 1'b0, 1'b0, "SLT: -1 < 1 is TRUE");

        inputA = 32'd1; inputB = -32'd1;
        check(32'd0, 1'b0, 1'b1, 1'b0, "SLT: 1 < -1 is FALSE");

        inputA = 32'h80000000; inputB = 32'h7FFFFFFF;
        check(32'd1, 1'b0, 1'b0, 1'b0, "SLT: MIN_INT < MAX_INT is TRUE");

        inputA = 32'h7FFFFFFF; inputB = 32'h80000000;
        check(32'd0, 1'b0, 1'b1, 1'b0, "SLT: MAX_INT < MIN_INT is FALSE");

        inputA = 32'd5; inputB = 32'd5;
        check(32'd0, 1'b0, 1'b1, 1'b0, "SLT: 5 < 5 is FALSE");

        ALUctrl = `ALU_sgt;
        inputA = 32'd1; inputB = -32'd1;
        check(32'd1, 1'b0, 1'b0, 1'b0, "SGT: 1 > -1 is TRUE");

        inputA = -32'd1; inputB = 32'd1;
        check(32'd0, 1'b0, 1'b1, 1'b0, "SGT: -1 > 1 is FALSE");

        inputA = 32'h7FFFFFFF; inputB = 32'h80000000;
        check(32'd1, 1'b0, 1'b0, 1'b0, "SGT: MAX_INT > MIN_INT is TRUE");

        inputA = 32'd5; inputB = 32'd5;
        check(32'd0, 1'b0, 1'b1, 1'b0, "SGT: 5 > 5 is FALSE");


        // default
        ALUctrl = `ALU_passb;
        inputA = 32'hDEADBEEF; inputB = 32'h12345678;
        check(32'h12345678, 1'b0, 1'b0, 1'b0, "PASSB: pass positive B");

        inputA = 32'hDEADBEEF; inputB = 32'h80000000;
        check(32'h80000000, 1'b0, 1'b0, 1'b1, "PASSB: pass negative B");

        inputA = 32'hDEADBEEF; inputB = 32'd0;
        check(32'd0, 1'b0, 1'b1, 1'b0, "PASSB: pass zero B");

        ALUctrl = 4'd15; // Undefined opcode
        inputA = 32'd10; inputB = 32'd20;
        check(32'd0, 1'b0, 1'b1, 1'b0, "DEFAULT: invalid ctrl produces 0");



        #5;
        if (errors == 0) begin
            $display("[PASS] alu_tb: all %0d tests passed successfully.", test_count);
        end else begin
            $display("[FAIL] alu_tb: %0d / %0d tests failed.", errors, test_count);
        end
        $finish;
    end

endmodule
`default_nettype wire
