// Copyright (c) Yug Bargaway under Apache License 2.0
// See LICENSE.txt for details.

// This file is generated by Gemini 3.8 flash, so this file uses LLM-generated code,
// rest files in rtl is written by me. Any issue you face, kindly mention in the issues
// sections in github.


`timescale 1ns / 1ps
`default_nettype none


`include "minirisc_defs.vh"


module control_unit_tb;

    reg [31:0] instr;

    wire [5:0] opcode;
    wire [3:0] rs1_addr;
    wire [3:0] rs2_addr;
    wire [3:0] rd_addr;

    wire [3:0] alu_ctrl;
    wire       alu_src_b;
    wire [2:0] imm_sel;
    wire       reg_write;
    wire       mem_read;
    wire       mem_write;
    wire [1:0] wb_sel;
    wire       is_halt;
    wire       is_branch;
    wire [1:0] br_type;
    wire       is_mul;
    wire       illegal;

    integer errors = 0;
    integer test_count = 0;

    // Device under test
    control_unit #(
        .INSTR_w(32),
        .OPCODE_w(6),
        .REGADDR_w(4)
    ) dut (
        .instr    (instr),
        .opcode   (opcode),
        .rs1_addr (rs1_addr),
        .rs2_addr (rs2_addr),
        .rd_addr  (rd_addr),
        .alu_ctrl (alu_ctrl),
        .alu_src_b(alu_src_b),
        .imm_sel  (imm_sel),
        .reg_write(reg_write),
        .mem_read (mem_read),
        .mem_write(mem_write),
        .wb_sel   (wb_sel),
        .is_halt  (is_halt),
        .is_branch(is_branch),
        .br_type  (br_type),
        .is_mul   (is_mul),
        .illegal  (illegal)
    );


    initial begin
        #50000;
        $display("FAIL: timeout");
        $finish;
    end


    initial begin
        $dumpfile("waves/control_unit_tb.vcd");
        $dumpvars(0, control_unit_tb);
    end


    task check_ctrl(
        input [5:0]       test_op,
        input [3:0]       exp_alu_ctrl,
        input             exp_alu_src_b,
        input [2:0]       exp_imm_sel,
        input             exp_reg_write,
        input             exp_mem_read,
        input             exp_mem_write,
        input [1:0]       exp_wb_sel,
        input             exp_is_halt,
        input             exp_is_branch,
        input             exp_is_mul,
        input             exp_illegal,
        input [160:0]     test_name
    );
    begin
        // Format instr: opcode in [31:26], rd=4 in [25:22], rs1=2 in [21:18], rs2=3 in [17:14]
        instr = {test_op, 4'd4, 4'd2, 4'd3, 14'd0};
        #1;
        test_count = test_count + 1;

        if (opcode !== test_op ||
            rs1_addr !== 4'd2 ||
            rs2_addr !== 4'd3 ||
            alu_ctrl !== exp_alu_ctrl ||
            alu_src_b !== exp_alu_src_b ||
            imm_sel !== exp_imm_sel ||
            reg_write !== exp_reg_write ||
            mem_read !== exp_mem_read ||
            mem_write !== exp_mem_write ||
            wb_sel !== exp_wb_sel ||
            is_halt !== exp_is_halt ||
            is_branch !== exp_is_branch ||
            is_mul !== exp_is_mul ||
            illegal !== exp_illegal) begin
            $display("FAIL [%0s]: op=%0b | Got: ctrl=%0d srcB=%0b immSel=%0d regWr=%0b memR=%0b memW=%0b wbSel=%0d halt=%0b br=%0b mul=%0b ill=%0b",
                     test_name, test_op, alu_ctrl, alu_src_b, imm_sel, reg_write, mem_read, mem_write, wb_sel, is_halt, is_branch, is_mul, illegal);
            errors = errors + 1;
        end
    end
    endtask


    initial begin
        // R-Type Instructions
        check_ctrl(`OP_add, `ALU_add, 1'b0, `IMM_none, 1'b1, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b0, 1'b0, 1'b0, "R-type: ADD");
        check_ctrl(`OP_sub, `ALU_sub, 1'b0, `IMM_none, 1'b1, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b0, 1'b0, 1'b0, "R-type: SUB");
        check_ctrl(`OP_and, `ALU_and, 1'b0, `IMM_none, 1'b1, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b0, 1'b0, 1'b0, "R-type: AND");
        check_ctrl(`OP_or,  `ALU_or,  1'b0, `IMM_none, 1'b1, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b0, 1'b0, 1'b0, "R-type: OR");
        check_ctrl(`OP_xor, `ALU_xor, 1'b0, `IMM_none, 1'b1, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b0, 1'b0, 1'b0, "R-type: XOR");
        check_ctrl(`OP_nor, `ALU_nor, 1'b0, `IMM_none, 1'b1, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b0, 1'b0, 1'b0, "R-type: NOR");
        check_ctrl(`OP_not, `ALU_not, 1'b0, `IMM_none, 1'b1, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b0, 1'b0, 1'b0, "R-type: NOT");
        check_ctrl(`OP_sll, `ALU_sll, 1'b0, `IMM_none, 1'b1, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b0, 1'b0, 1'b0, "R-type: SLL");
        check_ctrl(`OP_srl, `ALU_srl, 1'b0, `IMM_none, 1'b1, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b0, 1'b0, 1'b0, "R-type: SRL");
        check_ctrl(`OP_sra, `ALU_sra, 1'b0, `IMM_none, 1'b1, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b0, 1'b0, 1'b0, "R-type: SRA");
        check_ctrl(`OP_slt, `ALU_slt, 1'b0, `IMM_none, 1'b1, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b0, 1'b0, 1'b0, "R-type: SLT");
        check_ctrl(`OP_sgt, `ALU_sgt, 1'b0, `IMM_none, 1'b1, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b0, 1'b0, 1'b0, "R-type: SGT");

        // I-Type Instructions
        check_ctrl(`OP_addi, `ALU_add, 1'b1, `IMM_I_sext, 1'b1, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b0, 1'b0, 1'b0, "I-type: ADDI");
        check_ctrl(`OP_subi, `ALU_sub, 1'b1, `IMM_I_sext, 1'b1, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b0, 1'b0, 1'b0, "I-type: SUBI");
        check_ctrl(`OP_andi, `ALU_and, 1'b1, `IMM_I_zext, 1'b1, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b0, 1'b0, 1'b0, "I-type: ANDI");
        check_ctrl(`OP_ori,  `ALU_or,  1'b1, `IMM_I_zext, 1'b1, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b0, 1'b0, 1'b0, "I-type: ORI");
        check_ctrl(`OP_xori, `ALU_xor, 1'b1, `IMM_I_zext, 1'b1, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b0, 1'b0, 1'b0, "I-type: XORI");
        check_ctrl(`OP_slli, `ALU_sll, 1'b1, `IMM_I_zext, 1'b1, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b0, 1'b0, 1'b0, "I-type: SLLI");
        check_ctrl(`OP_srli, `ALU_srl, 1'b1, `IMM_I_zext, 1'b1, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b0, 1'b0, 1'b0, "I-type: SRLI");
        check_ctrl(`OP_srai, `ALU_sra, 1'b1, `IMM_I_zext, 1'b1, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b0, 1'b0, 1'b0, "I-type: SRAI");
        check_ctrl(`OP_inc,  `ALU_add, 1'b1, `IMM_one,    1'b1, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b0, 1'b0, 1'b0, "I-type: INC");
        check_ctrl(`OP_dec,  `ALU_sub, 1'b1, `IMM_one,    1'b1, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b0, 1'b0, 1'b0, "I-type: DEC");
        check_ctrl(`OP_lui,  `ALU_passb,1'b1,`IMM_lui,    1'b1, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b0, 1'b0, 1'b0, "I-type: LUI");

        // INC / DEC destination check
        instr = {`OP_inc, 4'd4, 4'd2, 4'd3, 14'd0};
        #1;
        test_count = test_count + 1;
        if (rd_addr !== 4'd2) begin
            $display("FAIL [INC rd_addr]: Expected rd=rs1=2, Got rd=%0d", rd_addr);
            errors = errors + 1;
        end

        // Memory
        check_ctrl(`OP_ld,   `ALU_add, 1'b1, `IMM_I_sext, 1'b1, 1'b1, 1'b0, `WB_mem, 1'b0, 1'b0, 1'b0, 1'b0, "MEM: LD");
        check_ctrl(`OP_st,   `ALU_add, 1'b1, `IMM_S_sext, 1'b0, 1'b0, 1'b1, `WB_alu, 1'b0, 1'b0, 1'b0, 1'b0, "MEM: ST");

        // Branch
        check_ctrl(`OP_b,    `ALU_add, 1'b0, `IMM_J_sext, 1'b0, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b1, 1'b0, 1'b0, "BRANCH: B");
        check_ctrl(`OP_bz,   `ALU_add, 1'b0, `IMM_S_sext, 1'b0, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b1, 1'b0, 1'b0, "BRANCH: BZ");
        check_ctrl(`OP_bltz, `ALU_add, 1'b0, `IMM_S_sext, 1'b0, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b1, 1'b0, 1'b0, "BRANCH: BLTZ");
        check_ctrl(`OP_bgtz, `ALU_add, 1'b0, `IMM_S_sext, 1'b0, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b1, 1'b0, 1'b0, "BRANCH: BGTZ");

        // Multiplier & Halt
        check_ctrl(`OP_halt, `ALU_add, 1'b0, `IMM_none,   1'b0, 1'b0, 1'b0, `WB_alu, 1'b1, 1'b0, 1'b0, 1'b0, "HALT");
        check_ctrl(`OP_mull, `ALU_add, 1'b0, `IMM_none,   1'b0, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b0, 1'b1, 1'b0, "MUL: MULL");
        check_ctrl(`OP_mulh, `ALU_add, 1'b0, `IMM_none,   1'b0, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b0, 1'b1, 1'b0, "MUL: MULH");
        check_ctrl(`OP_mac,  `ALU_add, 1'b0, `IMM_none,   1'b0, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b0, 1'b1, 1'b0, "MUL: MAC");

        // Illegal Opcodes
        check_ctrl(6'b11_1110, `ALU_add, 1'b0, `IMM_none, 1'b0, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b0, 1'b0, 1'b1, "ILLEGAL opcode");
        check_ctrl(6'b00_1111, `ALU_add, 1'b0, `IMM_none, 1'b0, 1'b0, 1'b0, `WB_alu, 1'b0, 1'b0, 1'b0, 1'b1, "UNDEFINED opcode");


        #5;
        if (errors == 0) begin
            $display("[PASS] control_unit_tb: all %0d tests passed successfully.", test_count);
        end else begin
            $display("[FAIL] control_unit_tb: %0d / %0d tests failed.", errors, test_count);
        end
        $finish;
    end

endmodule
`default_nettype wire
