// Copyright (c) Yug Bargaway under Apache License 2.0
// See LICENSE.txt for details.

// This file is generated by Gemini 3.8 flash, so this file uses LLM-generated code,
// rest files in rtl is written by me. Any issue you face, kindly mention in the issues
// sections in github.


`timescale 1ns / 1ps
`default_nettype none


`include "minirisc_defs.vh"


module data_out_mux_tb;

    localparam integer DATA_w = 32;

    reg  [DATA_w-1:0] ALUout;
    reg  [DATA_w-1:0] DataOut;
    reg  [DATA_w-1:0] OtherEndpoint;
    reg  [1:0]        RegInSrc;
    wire [DATA_w-1:0] RegIn;

    integer errors = 0;
    integer test_count = 0;

    // Device under test
    data_out_mux #(.DATA_w(DATA_w)) dut (
        .ALUout       (ALUout),
        .DataOut      (DataOut),
        .OtherEndpoint(OtherEndpoint),
        .RegInSrc     (RegInSrc),
        .RegIn        (RegIn)
    );


    initial begin #50000; $display("FAIL: timeout"); $finish; end

    initial begin
        $dumpfile("waves/data_out_mux_tb.vcd");
        $dumpvars(0, data_out_mux_tb);
    end

    task check(input [DATA_w-1:0] exp, input [160:0] name);
    begin
        #1; test_count = test_count + 1;
        if (RegIn !== exp) begin
            $display("FAIL [%0s]: RegInSrc=%0b | Got: 0x%08h | Expected: 0x%08h", name, RegInSrc, RegIn, exp);
            errors = errors + 1;
        end
    end
    endtask


    initial begin
        ALUout        = 32'hAAAAAAAA;
        DataOut       = 32'hBBBBBBBB;
        OtherEndpoint = 32'hCCCCCCCC;

        // WB_alu (2'd0) -> ALUout
        RegInSrc = `WB_alu;
        check(32'hAAAAAAAA, "WB_alu: selects ALUout");

        ALUout = 32'h12345678;
        RegInSrc = `WB_alu;
        check(32'h12345678, "WB_alu: updated ALUout");

        // WB_mem (2'd1) -> DataOut
        RegInSrc = `WB_mem;
        check(32'hBBBBBBBB, "WB_mem: selects DataOut");

        DataOut = 32'hDEADBEEF;
        RegInSrc = `WB_mem;
        check(32'hDEADBEEF, "WB_mem: updated DataOut");

        // WB_other (2'd2) -> OtherEndpoint
        RegInSrc = `WB_other;
        check(32'hCCCCCCCC, "WB_other: selects OtherEndpoint");

        OtherEndpoint = 32'h0A0B0C0D;
        RegInSrc = `WB_other;
        check(32'h0A0B0C0D, "WB_other: updated OtherEndpoint");

        // Default (2'd3) -> ALUout
        RegInSrc = 2'd3;
        check(32'h12345678, "DEFAULT: selects ALUout");


        #5;
        if (errors == 0) $display("[PASS] data_out_mux_tb: all %0d tests passed successfully.", test_count);
        else             $display("[FAIL] data_out_mux_tb: %0d / %0d tests failed.", errors, test_count);
        $finish;
    end

endmodule
`default_nettype wire
