// Copyright (c) Yug Bargaway under Apache License 2.0
// See LICENSE.txt for details.

// This file is generated by Gemini 3.8 flash, so this file uses LLM-generated code,
// rest files in rtl is written by me. Any issue you face, kindly mention in the issues
// sections in github.


`timescale 1ns / 1ps
`default_nettype none


module data_cache_tb;

    localparam integer ADDR_w = 32;
    localparam integer DATA_w = 32;
    localparam integer CACHE_words = 256;

    reg  clock;
    reg  reset;
    reg  [ADDR_w-1:0] DataAddr;
    reg  [DATA_w-1:0] DataIn;
    reg  DataRead;
    reg  DataWrite;

    wire [DATA_w-1:0] DataOut;

    integer errors = 0;
    integer test_count = 0;

    // Device under test
    data_cache #(
        .ADDR_w(ADDR_w),
        .DATA_w(DATA_w),
        .CACHE_words(CACHE_words),
        .INIT_file("")
    ) dut (
        .clock    (clock),
        .reset    (reset),
        .DataAddr (DataAddr),
        .DataIn   (DataIn),
        .DataRead (DataRead),
        .DataWrite(DataWrite),
        .DataOut  (DataOut)
    );

    // Clock: 10ns
    always #5 clock = ~clock;

    initial begin
        #50000;
        $display("FAIL: timeout");
        $finish;
    end

    initial begin
        $dumpfile("waves/data_cache_tb.vcd");
        $dumpvars(0, data_cache_tb);
    end


    task check(
        input [DATA_w-1:0] exp_data,
        input [160:0]      test_name
    );
    begin
        #1;
        test_count = test_count + 1;
        if (DataOut !== exp_data) begin
            $display("FAIL [%0s]: Addr=0x%08h Read=%0b Write=%0b | Got: 0x%08h | Expected: 0x%08h",
                     test_name, DataAddr, DataRead, DataWrite, DataOut, exp_data);
            errors = errors + 1;
        end
    end
    endtask


    initial begin
        clock = 0;
        reset = 1;
        DataAddr = 0;
        DataIn = 0;
        DataRead = 0;
        DataWrite = 0;

        // Reset
        @(negedge clock);
        reset = 1;
        @(negedge clock);
        reset = 0;

        // Read after reset with DataRead=1
        DataRead = 1;
        DataAddr = 32'd0;
        check(32'd0, "RESET: word 0 is zero");
        DataAddr = 32'd4;
        check(32'd0, "RESET: word 1 is zero");

        // DataRead = 0 outputs 0
        DataRead = 0;
        check(32'd0, "DATAREAD LOW: outputs 0");

        // Write word 0 (addr 0) and read back
        @(negedge clock);
        DataAddr = 32'd0;
        DataIn = 32'hDEADBEEF;
        DataWrite = 1;

        @(negedge clock);
        DataWrite = 0;
        DataRead = 1;
        check(32'hDEADBEEF, "WRITE/READ: word 0");

        // Word aligned addresses 1, 2, 3 should also read word 0
        DataAddr = 32'd1; check(32'hDEADBEEF, "ALIGNMENT: addr 1 reads word 0");
        DataAddr = 32'd2; check(32'hDEADBEEF, "ALIGNMENT: addr 2 reads word 0");
        DataAddr = 32'd3; check(32'hDEADBEEF, "ALIGNMENT: addr 3 reads word 0");

        // Sequential write to words 1, 2, 3
        @(negedge clock);
        DataAddr = 32'd4; DataIn = 32'h11111111; DataWrite = 1;
        @(negedge clock);
        DataAddr = 32'd8; DataIn = 32'h22222222; DataWrite = 1;
        @(negedge clock);
        DataAddr = 32'd12; DataIn = 32'h33333333; DataWrite = 1;

        @(negedge clock);
        DataWrite = 0;
        DataRead = 1;
        DataAddr = 32'd4;  check(32'h11111111, "READ: word 1");
        DataAddr = 32'd8;  check(32'h22222222, "READ: word 2");
        DataAddr = 32'd12; check(32'h33333333, "READ: word 3");

        // DataWrite = 0 prevents overwrite
        @(negedge clock);
        DataAddr = 32'd4; DataIn = 32'hFFFFFFFF; DataWrite = 0;
        @(negedge clock);
        DataAddr = 32'd4; DataRead = 1;
        check(32'h11111111, "WRITE LOW: word 1 unchanged");

        // Boundary word 255 (addr = 255 * 4 = 1020)
        @(negedge clock);
        DataAddr = 32'd1020; DataIn = 32'hCAFEBABE; DataWrite = 1;
        @(negedge clock);
        DataWrite = 0;
        DataRead = 1;
        DataAddr = 32'd1020;
        check(32'hCAFEBABE, "BOUNDARY: word 255");

        #10;
        if (errors == 0) begin
            $display("[PASS] data_cache_tb: all %0d tests passed successfully.", test_count);
        end else begin
            $display("[FAIL] data_cache_tb: %0d / %0d tests failed.", errors, test_count);
        end
        $finish;
    end

endmodule
`default_nettype wire
