// Copyright (c) Yug Bargaway under Apache License 2.0
// See LICENSE.txt for details.

// This file is generated by Gemini 3.8 flash, so this file uses LLM-generated code,
// rest files in rtl is written by me. Any issue you face, kindly mention in the issues
// sections in github.


`timescale 1ns / 1ps
`default_nettype none


`include "minirisc_defs.vh"


module imm_sign_extension_tb;

    reg  [31:0] instr;
    reg  [2:0]  imm_sel;
    wire [31:0] imm;

    integer errors = 0;
    integer test_count = 0;

    imm_sign_extension dut (
        .instr  (instr),
        .imm_sel(imm_sel),
        .imm    (imm)
    );

    initial begin
        #50000;
        $display("FAIL: timeout");
        $finish;
    end

    initial begin
        $dumpfile("waves/imm_sign_extension_tb.vcd");
        $dumpvars(0, imm_sign_extension_tb);
    end

    task check(
        input [31:0]  exp_imm,
        input [160:0] test_name
    );
    begin
        #1;
        test_count = test_count + 1;
        if (imm !== exp_imm) begin
            $display("FAIL [%0s]: instr=0x%08h imm_sel=%0d | Got: 0x%08h | Expected: 0x%08h",
                     test_name, instr, imm_sel, imm, exp_imm);
            errors = errors + 1;
        end
    end
    endtask


    initial begin
        // IMM_none
        instr = 32'hFFFFFFFF;
        imm_sel = `IMM_none;
        check(32'd0, "IMM_none: output 0");

        // IMM_I_sext (18-bit sign extension of instr[17:0])
        // Positive: 0x00010 -> 0x00000010
        instr = {14'd0, 18'h00010};
        imm_sel = `IMM_I_sext;
        check(32'h00000010, "IMM_I_sext: positive 18-bit immediate");

        // Negative: 0x20000 (bit 17 is 1) -> sign extend to 32 bits
        instr = {14'h3FFF, 18'h3FFFF}; // -1 in 18-bit
        imm_sel = `IMM_I_sext;
        check(32'hFFFFFFFF, "IMM_I_sext: negative -1");

        instr = {14'd0, 18'h20000}; // MSB of 18-bit is 1
        imm_sel = `IMM_I_sext;
        check(32'hFFFE0000, "IMM_I_sext: negative sign extend");

        // IMM_I_zext (18-bit zero extension)
        instr = {14'h3FFF, 18'h3FFFF};
        imm_sel = `IMM_I_zext;
        check(32'h0003FFFF, "IMM_I_zext: zero extension");

        // IMM_one (always 1)
        instr = 32'hDEADBEEF;
        imm_sel = `IMM_one;
        check(32'd1, "IMM_one: constant 1");

        // IMM_lui ({instr[13:0], 18'b0})
        instr = {18'd0, 14'h2A55};
        imm_sel = `IMM_lui;
        check({14'h2A55, 18'd0}, "IMM_lui: 14-bit shifted left by 18");

        // IMM_S_sext ({instr[25:22], instr[13:0]} -> 18-bit sign extended)
        // instr[25:22] = 4'h0, instr[13:0] = 14'h0005 -> 18'h00005 (pos)
        instr = {6'd0, 4'h0, 8'd0, 14'h0005};
        imm_sel = `IMM_S_sext;
        check(32'h00000005, "IMM_S_sext: positive");

        // Negative: MSB (instr[25]) = 1 -> 4'hF, 14'h3FFF
        instr = {6'd0, 4'hF, 8'd0, 14'h3FFF};
        imm_sel = `IMM_S_sext;
        check(32'hFFFFFFFF, "IMM_S_sext: negative -1");

        // IMM_J_sext (22-bit sign extension of instr[21:0])
        instr = {10'd0, 22'h000100};
        imm_sel = `IMM_J_sext;
        check(32'h00000100, "IMM_J_sext: positive");

        // Negative: bit 21 = 1
        instr = {10'd0, 22'h200000};
        imm_sel = `IMM_J_sext;
        check(32'hFFE00000, "IMM_J_sext: negative sign extend");

        // Default
        imm_sel = 3'd7;
        check(32'd0, "DEFAULT: invalid imm_sel");


        #5;
        if (errors == 0) begin
            $display("[PASS] imm_sign_extension_tb: all %0d tests passed successfully.", test_count);
        end else begin
            $display("[FAIL] imm_sign_extension_tb: %0d / %0d tests failed.", errors, test_count);
        end
        $finish;
    end

endmodule
`default_nettype wire
