// Copyright (c) Yug Bargaway under Apache License 2.0
// See LICENSE.txt for details.

// This file is generated by Gemini 3.8 flash, so this file uses LLM-generated code,
// rest files in rtl is written by me. Any issue you face, kindly mention in the issues
// sections in github.


`timescale 1ns / 1ps
`default_nettype none


module instruction_cache_tb;

    localparam integer PC_w = 32;
    localparam integer WORD_w = 32;
    localparam integer CACHE_words = 256;

    reg  [PC_w-1:0]   PC;
    wire [WORD_w-1:0] Instruction;

    integer errors = 0;
    integer test_count = 0;
    integer i;

    instruction_cache #(
        .PC_w(PC_w),
        .WORD_w(WORD_w),
        .CACHE_words(CACHE_words),
        .INIT_file("")
    ) dut (
        .PC(PC),
        .Instruction(Instruction)
    );

    initial begin
        #50000;
        $display("FAIL: timeout");
        $finish;
    end

    initial begin
        $dumpfile("waves/instruction_cache_tb.vcd");
        $dumpvars(0, instruction_cache_tb);
    end

    task check(
        input [WORD_w-1:0] exp_data,
        input [160:0]      test_name
    );
    begin
        #1;
        test_count = test_count + 1;
        if (Instruction !== exp_data) begin
            $display("FAIL [%0s]: PC=0x%08h | Got: 0x%08h | Expected: 0x%08h",
                     test_name, PC, Instruction, exp_data);
            errors = errors + 1;
        end
    end
    endtask

    initial begin
        // Initialize memory with predictable test patterns
        for (i = 0; i < CACHE_words; i = i + 1) begin
            dut.memory[i] = 32'h10000000 + i;
        end

        // Check word 0 at PC = 0, 1, 2, 3 (word aligned addressing)
        PC = 32'd0; check(32'h10000000, "PC=0 (Word 0)");
        PC = 32'd1; check(32'h10000000, "PC=1 (Word 0 offset 1)");
        PC = 32'd2; check(32'h10000000, "PC=2 (Word 0 offset 2)");
        PC = 32'd3; check(32'h10000000, "PC=3 (Word 0 offset 3)");

        // Sequential words
        PC = 32'd4;  check(32'h10000001, "PC=4 (Word 1)");
        PC = 32'd8;  check(32'h10000002, "PC=8 (Word 2)");
        PC = 32'd12; check(32'h10000003, "PC=12 (Word 3)");

        // Index boundary test (word 255 -> byte address 255 * 4 = 1020)
        PC = 32'd1020; check(32'h100000FF, "PC=1020 (Word 255)");


        #5;
        if (errors == 0) begin
            $display("[PASS] instruction_cache_tb: all %0d tests passed successfully.", test_count);
        end else begin
            $display("[FAIL] instruction_cache_tb: %0d / %0d tests failed.", errors, test_count);
        end
        $finish;
    end

endmodule
`default_nettype wire
