// Copyright (c) Yug Bargaway under Apache License 2.0
// See LICENSE.txt for details.

// This file is generated by Gemini 3.8 flash, so this file uses LLM-generated code,
// rest files in rtl is written by me. Any issue you face, kindly mention in the issues
// sections in github.


`timescale 1ns / 1ps
`default_nettype none


`include "minirisc_defs.vh"


module next_address_tb;

    localparam integer PC_w = 32;
    localparam integer DATA_w = 32;
    localparam integer JTA_w = 26;
    localparam integer IMM_w = 16;

    reg  [PC_w-1:0]   PC;
    reg  [DATA_w-1:0] rs;
    reg  [DATA_w-1:0] rt;
    reg  [JTA_w-1:0]  jta;
    reg  [IMM_w-1:0]  branch_imm;
    reg  [PC_w-1:0]   syscall_addr;
    reg  [1:0]        pc_src;
    reg  [1:0]        br_type;

    wire [PC_w-1:0]   NextPC;
    wire [PC_w-1:0]   IncrPC;

    integer errors = 0;
    integer test_count = 0;

    // Device under test
    next_address #(
        .PC_w(PC_w),
        .DATA_w(DATA_w),
        .JTA_w(JTA_w),
        .IMM_w(IMM_w)
    ) dut (
        .PC          (PC),
        .rs          (rs),
        .rt          (rt),
        .jta         (jta),
        .branch_imm  (branch_imm),
        .syscall_addr(syscall_addr),
        .pc_src      (pc_src),
        .br_type     (br_type),
        .NextPC      (NextPC),
        .IncrPC      (IncrPC)
    );

    initial begin
        #50000;
        $display("FAIL: timeout");
        $finish;
    end

    initial begin
        $dumpfile("waves/next_address_tb.vcd");
        $dumpvars(0, next_address_tb);
    end

    task check(
        input [PC_w-1:0] exp_next,
        input [PC_w-1:0] exp_incr,
        input [160:0]    test_name
    );
    begin
        #1;
        test_count = test_count + 1;
        if (NextPC !== exp_next || IncrPC !== exp_incr) begin
            $display("FAIL [%0s]: Got NextPC=0x%08h IncrPC=0x%08h | Expected NextPC=0x%08h IncrPC=0x%08h",
                     test_name, NextPC, IncrPC, exp_next, exp_incr);
            errors = errors + 1;
        end
    end
    endtask


    initial begin
        PC = 0;
        rs = 0;
        rt = 0;
        jta = 0;
        branch_imm = 0;
        syscall_addr = 0;
        pc_src = `PCSRC_incr;
        br_type = `BRTYPE_eq;

        // Sequential increment
        // PC = 0 -> IncrPC = 1 (word address increment: PC[31:2] + 1 = 1)
        PC = 32'h00000000;
        pc_src = `PCSRC_incr;
        check(32'd1, 32'd1, "INCR: PC=0 -> NextPC=1");

        PC = 32'd4; // word address 1
        check(32'd2, 32'd2, "INCR: PC=4 -> NextPC=2");

        // Branch equal (BRTYPE_eq) TAKEN (rs == rt)
        // branch_target = IncrPC + sign_ext(branch_imm)
        // PC = 0 -> IncrPC = 1, branch_imm = 5 -> target = 6
        PC = 32'd0;
        rs = 32'd42; rt = 32'd42;
        branch_imm = 16'd5;
        br_type = `BRTYPE_eq;
        pc_src = `PCSRC_branch;
        check(32'd6, 32'd1, "BRANCH EQUAL: taken forward (+5)");

        // Backward branch (-3)
        // IncrPC = 1 + (-3) = -2 (as 30-bit: 0x3FFFFFFE)
        branch_imm = -16'd3;
        check(32'h3FFFFFFE, 32'd1, "BRANCH EQUAL: taken backward (-3)");

        // Branch equal NOT TAKEN (rs != rt)
        rs = 32'd42; rt = 32'd99;
        branch_imm = 16'd5;
        check(32'd1, 32'd1, "BRANCH EQUAL: not taken -> NextPC = IncrPC");

        // Branch not equal (BRTYPE_ne) TAKEN (rs != rt)
        rs = 32'd42; rt = 32'd99;
        branch_imm = 16'd10;
        br_type = `BRTYPE_ne;
        check(32'd11, 32'd1, "BRANCH NOT EQUAL: taken forward (+10)");

        // Branch not equal NOT TAKEN (rs == rt)
        rs = 32'd42; rt = 32'd42;
        check(32'd1, 32'd1, "BRANCH NOT EQUAL: not taken -> NextPC = IncrPC");

        // Jump (PCSRC_jump)
        // jump_target = {PC[31:28], jta}
        PC = 32'h10000000; // top 4 bits: 4'h1
        jta = 26'h03FFFFF;
        pc_src = `PCSRC_jump;
        check({4'h1, 26'h03FFFFF}, 32'h04000001, "JUMP: jump_target formation");

        // Syscall (PCSRC_syscall)
        syscall_addr = 32'h00000100;
        pc_src = `PCSRC_syscall;
        check(32'h00000100, 32'h04000001, "SYSCALL: syscall_addr");


        #5;
        if (errors == 0) begin
            $display("[PASS] next_address_tb: all %0d tests passed successfully.", test_count);
        end else begin
            $display("[FAIL] next_address_tb: %0d / %0d tests failed.", errors, test_count);
        end
        $finish;
    end

endmodule
`default_nettype wire
