// Copyright (c) Yug Bargaway under Apache License 2.0
// See LICENSE.txt for details.

// This file is generated by Gemini 3.8 flash, so this file uses LLM-generated code,
// rest files in rtl is written by me. Any issue you face, kindly mention in the issues
// sections in github.


`timescale 1ns / 1ps
`default_nettype none

module reg_file_tb;

    localparam integer WORD_w = 32;
    localparam integer REG_w = 4;
    localparam integer REG_count = (1 << REG_w);

    reg clock;
    reg RegWrite;
    reg reset;
    reg [REG_w-1:0] rs_add;
    reg [REG_w-1:0] rt_add;
    reg [REG_w-1:0] rw_add;
    reg [WORD_w-1:0] data;

    wire [WORD_w-1:0] rs_data;
    wire [WORD_w-1:0] rt_data;

    integer errors = 0;
    integer test_count = 0;
    integer i;

    // Device under test
    reg_file #(
        .WORD_w(WORD_w),
        .REG_w(REG_w)
    ) dut (
        .clock   (clock),
        .RegWrite(RegWrite),
        .reset   (reset),
        .rs_add  (rs_add),
        .rt_add  (rt_add),
        .rw_add  (rw_add),
        .data    (data),
        .rs_data (rs_data),
        .rt_data (rt_data)
    );

    // Clock generation: 10ns period
    always #5 clock = ~clock;

    // Watchdog
    initial begin
        #50000;
        $display("FAIL: timeout");
        $finish;
    end

    // Waveform
    initial begin
        $dumpfile("waves/reg_file_tb.vcd");
        $dumpvars(0, reg_file_tb);
    end

    task check(
        input [WORD_w-1:0] exp_rs,
        input [WORD_w-1:0] exp_rt,
        input [160:0]      test_name
    );
    begin
        #1;
        test_count = test_count + 1;
        if (rs_data !== exp_rs || rt_data !== exp_rt) begin
            $display("FAIL mismatch in [%0s]: rs=%0d rt=%0d | Got rs_data=0x%08h rt_data=0x%08h | Expected rs_data=0x%08h rt_data=0x%08h",
                     test_name, rs_add, rt_add, rs_data, rt_data, exp_rs, exp_rt);
            errors = errors + 1;
        end
    end
    endtask

    initial begin
        clock = 0;
        reset = 1;
        RegWrite = 0;
        rs_add = 0;
        rt_add = 0;
        rw_add = 0;
        data = 0;

        // Reset check
        @(negedge clock);
        reset = 1;
        @(negedge clock);
        reset = 0;
        for (i = 0; i < REG_count; i = i + 1) begin
            rs_add = i[REG_w-1:0];
            rt_add = i[REG_w-1:0];
            check(32'd0, 32'd0, "RESET: all registers zero");
        end

        // Write each register
        for (i = 0; i < REG_count; i = i + 1) begin
            @(negedge clock);
            rw_add = i[REG_w-1:0];
            data = 32'hA0000000 + i;
            RegWrite = 1;
        end

        @(negedge clock);
        RegWrite = 0;
        #1;

        // Read back on rs and rt
        for (i = 0; i < REG_count; i = i + 1) begin
            rs_add = i[REG_w-1:0];
            rt_add = i[REG_w-1:0];
            check(32'hA0000000 + i, 32'hA0000000 + i, "WRITE/READ: verify register");
        end

        // Dual read ports simultaneously
        rs_add = 4'd2;
        rt_add = 4'd7;
        check(32'hA0000002, 32'hA0000007, "DUAL READ: R2 and R7");

        rs_add = 4'd15;
        rt_add = 4'd0;
        check(32'hA000000F, 32'hA0000000, "DUAL READ: R15 and R0");

        // RegWrite = 0 should not write
        @(negedge clock);
        rw_add = 4'd5;
        data = 32'hDEADBEEF;
        RegWrite = 0;

        @(posedge clock);
        #1;
        rs_add = 4'd5;
        rt_add = 4'd5;
        check(32'hA0000005, 32'hA0000005, "WRITE ENABLE LOW: R5 unchanged");

        // Reset during operation
        @(negedge clock);
        reset = 1;
        @(posedge clock);
        #1;
        reset = 0;
        rs_add = 4'd2;
        rt_add = 4'd7;
        check(32'd0, 32'd0, "RESET AFTER WRITE: cleared");

        #10;
        if (errors == 0) begin
            $display("[PASS] reg_file_tb: all %0d tests passed successfully.", test_count);
        end else begin
            $display("[FAIL] reg_file_tb: %0d / %0d tests failed.", errors, test_count);
        end
        $finish;
    end

endmodule
`default_nettype wire
