# Copyright (c) Yug Bargaway under Apache License 2.0
# See LICENSE.txt for details.

# This file is generated by Gemini 3.8 flash, so this file uses LLM-generated code,
# rest files in rtl is written by me. Any issue you face, kindly mention in the issues
# sections in github.


IVERILOG ?= iverilog
VVP      ?= vvp
TOP      ?= soc_top
HEX      ?=

BUILD    := build
RTL      := $(shell find rtl -name '*.v')
TB_FILES := $(wildcard tb/unit/*_tb.v) $(wildcard tb/system/*_tb.v)
TB_NAMES := $(basename $(notdir $(TB_FILES)))
IVFLAGS  := -g2012 -Wall -Irtl/include

vpath %_tb.v tb/unit tb/system

.PHONY: help preset compile test lint clean
.PRECIOUS: $(BUILD)/%.vvp

help:
	@echo "make help                  print this help message"
	@echo "make preset                install/check prerequisites and build the assembler"
	@echo "make compile [TOP=...]     check syntax/elaboration with iverilog (default: TOP=$(TOP))"
	@echo "make lint [TOP=...]        Verilator lint of rtl/ (default: TOP=$(TOP))"
	@echo "make test                  run all testbenches, PASS/FAIL summary"
	@echo "make run-<tb> [HEX=...]    build and run one testbench (e.g. run-alu_tb)"
	@echo "make wave-<tb>             run, then open waves/<tb>.vcd in GTKWave"
	@echo "make clean                 remove build output and waveforms"

preset:
	bash prerequisites.sh
	$(MAKE) -C assember

compile:
	$(IVERILOG) $(IVFLAGS) -tnull -s $(TOP) $(RTL)

lint:
	verilator --lint-only -Wall -Irtl/include $(RTL) --top-module $(TOP)

$(BUILD)/%.vvp: %.v $(RTL)
	@mkdir -p $(BUILD) waves
	$(IVERILOG) $(IVFLAGS) -s $* -o $@ $< $(RTL)

run-%: $(BUILD)/%.vvp
	$(VVP) $< $(if $(HEX),+HEX=$(HEX))

wave-%: run-%
	env -u GTK_PATH -u GTK_EXE_PREFIX -u GTK_IM_MODULE_FILE gtkwave waves/$*.vcd &

test:
	@fail=0; \
	for t in $(TB_NAMES); do \
	  $(MAKE) -s $(BUILD)/$$t.vvp || { echo "[BUILD FAIL] $$t"; fail=1; continue; }; \
	  out=$$($(VVP) $(BUILD)/$$t.vvp 2>&1); \
	  if echo "$$out" | grep -q "FAIL" || ! echo "$$out" | grep -q "PASS"; then \
	    echo "[FAIL] $$t"; echo "$$out" | grep "FAIL" | head -5; fail=1; \
	  else echo "[PASS] $$t"; fi; \
	done; exit $$fail

clean:
	rm -rf $(BUILD) waves/*.vcd
