# Copyright (c) Yug Bargaway under Apache License 2.0
# See LICENSE.txt for details.

# This file is generated by Gemini 3.8 flash, so this file uses LLM-generated code,
# rest files in rtl is written by me. Any issue you face, kindly mention in the issues
# sections in github.



#!/usr/bin/bash


# MiniMIPS Prerequisites Check & Installer Script
# Checks required dependencies and prompts the user before installing any missing ones.

set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'


prompt_and_install() {
    local name="$1"
    local install_cmd="$2"

    echo -e "${YELLOW}[MISSING]${NC} '$name' is not installed."
    
    # Prompt user
    if [ -t 0 ]; then
        read -r -p "Would you like to install '$name'? [y/N]: " choice
    else
        read -r -p "Would you like to install '$name'? [y/N]: " choice < /dev/tty || choice="n"
    fi

    case "$choice" in
        [yY]|[yY][eE][sS])
            echo -e "${BLUE}[INSTALLING]${NC} Running: $install_cmd"
            eval "$install_cmd"
            echo -e "${GREEN}[INSTALLED]${NC} '$name' successfully installed."
            ;;
        *)
            echo -e "${RED}[ABORTED]${NC} Installation of '$name' declined. Aborting setup."
            exit 1
            ;;
    esac
}


get_version() {
    local cmd="$1"
    case "$cmd" in
        iverilog|vvp)
            $cmd -V 2>&1 | head -n 1
            ;;
        *)
            $cmd --version 2>&1 | head -n 1
            ;;
    esac
}


check_cmd() {
    local name="$1"
    local cmd="$2"
    local install_cmd="$3"

    echo -n "Checking for $name ($cmd)... "
    if command -v "$cmd" >/dev/null 2>&1; then
        local ver_info
        ver_info=$(get_version "$cmd")
        echo -e "${GREEN}[OK]${NC} ($ver_info)"
    else
        echo ""
        prompt_and_install "$name" "$install_cmd"
    fi
}


check_python_module() {
    local module="$1"
    local install_cmd="$2"

    echo -n "Checking for Python module '$module'... "
    if python3 -c "import $module" >/dev/null 2>&1; then
        local ver
        ver=$(python3 -c "import $module; print(getattr($module, '__version__', 'available'))")
        echo -e "${GREEN}[OK]${NC} (version: $ver)"
    else
        echo ""
        prompt_and_install "Python module $module" "$install_cmd"
    fi
}


echo "-------------------------------------------------"
echo " MiniMIPS Dependency Check"
echo "-------------------------------------------------"

# GNU Make
check_cmd "GNU Make" "make" "sudo apt-get update && sudo apt-get install -y make"

# Icarus Verilog & runtime
check_cmd "Icarus Verilog" "iverilog" "sudo apt-get update && sudo apt-get install -y iverilog"
check_cmd "Icarus Runtime (vvp)" "vvp" "sudo apt-get update && sudo apt-get install -y iverilog"

# GTKWave
check_cmd "GTKWave" "gtkwave" "sudo apt-get update && sudo apt-get install -y gtkwave"

# Verilator
check_cmd "Verilator" "verilator" "sudo apt-get update && sudo apt-get install -y verilator"

# Python 3
check_cmd "Python 3" "python3" "sudo apt-get update && sudo apt-get install -y python3"

# Python pip
check_cmd "Python Pip" "pip" "sudo apt-get update && sudo apt-get install -y python3-pip"

# Matplotlib (with compatible numpy)
check_python_module "matplotlib" "python3 -m pip install 'numpy<2' matplotlib --break-system-packages"

echo "----------------------------------------------------"
echo -e "${GREEN}All prerequisites are satisfied!${NC}"
echo "----------------------------------------------------"
